version: "3.8"

services:
  api:
    container_name: eulabs-api
    build:
      context: .
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
  db:
    container_name: eulabs-db
    image: mysql:8.2.0
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - eulabs:/var/lib/mysql

volumes:
  eulabs:
